Repository aconno/Sensorics, pull requests merged in 2019-07, with the labels that each got.

#187 Fix multiple action issue
  domain/src/main/java/com/aconno/sensorics/domain/format/FormatMatcher.kt
Labels: bug

#195 Fix tests, add action activation/deactivation
  app/src/main/java/com/aconno/sensorics/adapter/ActionAdapter.kt
  app/src/main/java/com/aconno/sensorics/dagger/application/AppModule.kt
  app/src/main/java/com/aconno/sensorics/dagger/mainactivity/MainActivityModule.kt
  app/src/main/java/com/aconno/sensorics/ui/actions/ActionDetailsActivity.kt
  app/src/main/java/com/aconno/sensorics/ui/actions/ActionDetailsViewModel.kt
  app/src/main/java/com/aconno/sensorics/ui/devices/SavedDevicesFragment.kt
  app/src/main/res/layout/activity_action_details.xml
  app/src/main/res/layout/item_action.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle
  data/src/main/java/com/aconno/sensorics/data/repository/SensoricsDatabase.kt
  data/src/main/java/com/aconno/sensorics/data/repository/action/ActionDao.kt
  data/src/main/java/com/aconno/sensorics/data/repository/action/ActionEntity.kt
  data/src/main/java/com/aconno/sensorics/data/repository/action/ActionsRepositoryImpl.kt
  domain/src/main/java/com/aconno/sensorics/domain/actions/Action.kt
  domain/src/main/java/com/aconno/sensorics/domain/actions/ActionsRepository.kt
  domain/src/main/java/com/aconno/sensorics/domain/actions/GeneralAction.kt
  domain/src/main/java/com/aconno/sensorics/domain/interactor/ifttt/InputToOutcomesUseCase.kt
  domain/src/main/java/com/aconno/sensorics/domain/interactor/ifttt/action/GetActionsByDeviceMacAddressUseCase.kt
  domain/src/main/java/com/aconno/sensorics/domain/interactor/ifttt/action/SetActionActiveByDeviceMacAddressUseCase.kt
  domain/src/main/java/com/aconno/sensorics/domain/interactor/type/CompletableUseCaseWithTwoParameters.kt
  domain/src/test/java/com/aconno/sensorics/domain/Util.kt
  domain/src/test/java/com/aconno/sensorics/domain/interactor/repository/GetActionsByDeviceMacAddressUseCaseTest.kt
  domain/src/test/java/com/aconno/sensorics/domain/interactor/repository/SetActionActiveByDeviceMacAddressUseCaseTest.kt
Labels: bug, enhancement, feature

#197 Action timeframe feature & Equal condition fix
  app/build.gradle
  app/src/main/java/com/aconno/sensorics/SensoricsApplication.kt
  app/src/main/java/com/aconno/sensorics/dagger/application/AppModule.kt
  app/src/main/java/com/aconno/sensorics/dagger/bluetoothscanning/BluetoothScanningServiceModule.kt
  app/src/main/java/com/aconno/sensorics/ui/actions/ActionDetailsActivity.kt
  app/src/main/java/com/aconno/sensorics/ui/actions/ActionDetailsViewModel.kt
  app/src/main/res/layout/activity_action_details.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  build.gradle
  data/src/main/java/com/aconno/sensorics/data/repository/SensoricsDatabase.kt
  data/src/main/java/com/aconno/sensorics/data/repository/action/ActionEntity.kt
  data/src/main/java/com/aconno/sensorics/data/repository/action/ActionsRepositoryImpl.kt
  device/build.gradle
  device/src/main/java/com/aconno/sensorics/device/time/TimeProviderImpl.kt
  domain/src/main/java/com/aconno/sensorics/domain/actions/Action.kt
  domain/src/main/java/com/aconno/sensorics/domain/actions/GeneralAction.kt
  domain/src/main/java/com/aconno/sensorics/domain/interactor/ifttt/InputToOutcomesUseCase.kt
  domain/src/main/java/com/aconno/sensorics/domain/interactor/ifttt/action/SetActionActiveByDeviceMacAddressUseCase.kt
  domain/src/main/java/com/aconno/sensorics/domain/interactor/time/GetLocalTimeOfDayInSecondsUseCase.kt
  domain/src/main/java/com/aconno/sensorics/domain/time/TimeProvider.kt
  domain/src/test/java/com/aconno/sensorics/domain/time/GetLocalTimeOfDayInSecondsUseCaseTest.kt
Labels: bug, enhancement, feature

#192 Add embeddable RSSI to backend
  app/src/main/res/values/strings.xml
  build.gradle
  data/src/main/java/com/aconno/sensorics/data/converter/DataStringConverter.kt
  data/src/main/java/com/aconno/sensorics/data/publisher/RestPublisher.kt
  data/src/test/java/com/aconno/sensorics/data/DataStringConverterTest.kt
  domain/src/main/java/com/aconno/sensorics/domain/interactor/consolidation/GenerateReadingsUseCase.kt
  domain/src/main/java/com/aconno/sensorics/domain/model/Reading.kt
Labels: enhancement

#199 Update Kotlin version
  build.gradle
Labels: enhancement

#201 acnSchmersal
  app/src/main/assets/resources/configs/F000.config
  app/src/main/assets/resources/device_screens/acnschmersal.html
  app/src/main/assets/resources/formats/F000.json
  app/src/main/assets/resources/icons/ic_schmersal.png
  data/src/main/java/com/aconno/sensorics/data/repository/resources/ResourcesRepositoryImpl.kt
Labels: feature

#203 Deserializer tests added
  domain/src/main/java/com/aconno/sensorics/domain/format/SupportedTypes.kt
  domain/src/main/java/com/aconno/sensorics/domain/serialization/DeserializerImpl.kt
  domain/src/test/java/com/aconno/sensorics/domain/deserializer/DeserializerTest.kt
Labels: enhancement, feature

#209 Updated deserializer format
  data/src/main/java/com/aconno/sensorics/data/mapper/FormatJsonConverter.kt
  data/src/main/java/com/aconno/sensorics/data/repository/resources/format/ByteFormatJsonModel.kt
  data/src/main/java/com/aconno/sensorics/data/repository/resources/format/ByteFormatRequiredJsonModel.kt
  domain/src/main/java/com/aconno/sensorics/domain/ByteOperations.kt
  domain/src/main/java/com/aconno/sensorics/domain/format/ByteFormat.kt
  domain/src/main/java/com/aconno/sensorics/domain/format/ByteFormatRequired.kt
  domain/src/main/java/com/aconno/sensorics/domain/format/FormatMatcher.kt
  domain/src/test/java/com/aconno/sensorics/domain/ByteOperationsTest.kt
  domain/src/test/java/com/aconno/sensorics/domain/Util.kt
  domain/src/test/java/com/aconno/sensorics/domain/format/FormatMatcherTest.kt
Labels: enhancement, feature

#207 Added slide delete to PublishListFragment
  app/src/main/java/com/aconno/sensorics/ui/settings/publishers/PublishListFragment.kt
  app/src/main/java/com/aconno/sensorics/ui/settings/publishers/PublishRecyclerViewAdapter.kt
  app/src/main/res/layout/fragment_publish_list.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, feature

#205 Add alarm outcome
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/aconno/sensorics/AlarmService.kt
  app/src/main/java/com/aconno/sensorics/AlarmServiceControllerImpl.kt
  app/src/main/java/com/aconno/sensorics/CpuWakeLock.kt
  app/src/main/java/com/aconno/sensorics/IntentProviderImpl.kt
  app/src/main/java/com/aconno/sensorics/dagger/alarm/AlarmServiceModule.kt
  app/src/main/java/com/aconno/sensorics/dagger/alarm/AlarmServiceScope.kt
  app/src/main/java/com/aconno/sensorics/dagger/application/ActivityBuilder.kt
  app/src/main/java/com/aconno/sensorics/dagger/application/AppModule.kt
  app/src/main/java/com/aconno/sensorics/dagger/bluetoothscanning/BluetoothScanningServiceModule.kt
  app/src/main/java/com/aconno/sensorics/ui/actions/ActionDetailsActivity.kt
  app/src/main/res/layout/activity_action_details.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  device/src/main/java/com/aconno/sensorics/device/AudioAlarmImpl.kt
  device/src/main/java/com/aconno/sensorics/device/DeviceAudioManagerImpl.kt
  device/src/main/java/com/aconno/sensorics/device/DeviceTelephonyManagerImpl.kt
  device/src/main/java/com/aconno/sensorics/device/notification/NotificationFactory.kt
  domain/src/main/java/com/aconno/sensorics/domain/AlarmServiceController.kt
  domain/src/main/java/com/aconno/sensorics/domain/AudioAlarm.kt
  domain/src/main/java/com/aconno/sensorics/domain/DeviceAudioManager.kt
  domain/src/main/java/com/aconno/sensorics/domain/actions/outcomes/Outcome.kt
  domain/src/main/java/com/aconno/sensorics/domain/ifttt/outcome/RunOutcomeUseCase.kt
  domain/src/main/java/com/aconno/sensorics/domain/telephony/CallStateListener.kt
  domain/src/main/java/com/aconno/sensorics/domain/telephony/DeviceTelephonyManager.kt
Labels: enhancement, feature

#211 Publisher fixes
  app/src/main/java/com/aconno/sensorics/PublisherIntervalConverter.kt
  app/src/main/res/layout/layout_publisher_header.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/aconno/sensorics/data/converter/DataStringConverter.kt
  data/src/main/java/com/aconno/sensorics/data/publisher/RestPublisher.kt
Labels: bug, enhancement, feature

#213 Add RSSI to acnSchmersal & Add rssi value to onSensorReadings call
  app/src/main/assets/resources/device_screens/acnschmersal.html
  app/src/main/java/com/aconno/sensorics/ui/device_main/DeviceMainFragment.kt
Labels: enhancement, feature
