Repository aconno/Sensorics, pull requests merged in 2019-04, with the labels that each got.

#153 Fix AcnSensa format path change
  app/src/main/assets/resources/configs/0800.config
  app/src/main/assets/resources/configs/0801.config
Labels: bug

#155 Timber logs should only be available in the "dev" build flavor
  app/src/main/java/com/aconno/sensorics/SensoricsApplication.kt
Labels: bug

#156 Add jquery.min.js into assets for Offline Support
  app/src/main/assets/resources/html_resources/jquery-3.3.1.min.js
  app/src/main/assets/resources/usecase_screens/acnrange.html
Labels: bug

#157 Fix ReplaySubject to BehaviorSubject in InMemoryRepository
  data/src/main/java/com/aconno/sensorics/data/repository/InMemoryRepositoryImpl.kt
Labels: bug

#159 Fix viewpager2 vertical scroll
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/aconno/sensorics/adapter/viewpager2/ViewPager2TouchHelper.kt
  app/src/main/java/com/aconno/sensorics/adapter/viewpager2/ViewPagerAdapter.kt
  app/src/main/java/com/aconno/sensorics/ui/MainActivity2.kt
  app/src/main/java/com/aconno/sensorics/ui/device_main/DeviceMainFragment.kt
  app/src/main/java/com/aconno/sensorics/viewmodel/SplashViewModel.kt
  app/src/main/res/drawable/tabl_selector.xml
  app/src/main/res/layout/activity_toolbar2.xml
  app/src/main/res/layout/fragment_device_main.xml
  app/src/main/res/menu/menu_readings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: bug

#160 Fix Scanning known beacon but no has invalid data
  domain/src/main/java/com/aconno/sensorics/domain/interactor/consolidation/GenerateReadingsUseCase.kt
Labels: bug

#163 Revert to Old ViewPager implementation
  app/build.gradle
  app/src/main/java/com/aconno/sensorics/adapter/viewpager/ViewPagerAdapter.kt
  app/src/main/java/com/aconno/sensorics/adapter/viewpager2/FragmentStateAdapter.kt
  app/src/main/java/com/aconno/sensorics/adapter/viewpager2/FragmentViewHolder.kt
  app/src/main/java/com/aconno/sensorics/adapter/viewpager2/TabLayoutMediator.java
  app/src/main/java/com/aconno/sensorics/adapter/viewpager2/ViewPager2TouchHelper.kt
  app/src/main/java/com/aconno/sensorics/ui/MainActivity2.kt
  app/src/main/java/com/aconno/sensorics/ui/device_main/DeviceMainFragment.kt
  app/src/main/java/com/aconno/sensorics/viewmodel/DeviceViewModel.kt
  app/src/main/res/layout/activity_toolbar2.xml
Labels: bug

#164 Beacon status
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/aconno/sensorics/adapter/viewpager/ViewPagerAdapter.kt
  app/src/main/java/com/aconno/sensorics/adapter/viewpager2/FragmentStateAdapter.kt
  app/src/main/java/com/aconno/sensorics/adapter/viewpager2/FragmentViewHolder.kt
  app/src/main/java/com/aconno/sensorics/adapter/viewpager2/TabLayoutMediator.java
  app/src/main/java/com/aconno/sensorics/adapter/viewpager2/ViewPager2TouchHelper.kt
  app/src/main/java/com/aconno/sensorics/adapter/viewpager2/ViewPagerAdapter.kt
  app/src/main/java/com/aconno/sensorics/ui/MainActivity2.kt
  app/src/main/java/com/aconno/sensorics/ui/device_main/DeviceMainFragment.kt
  app/src/main/java/com/aconno/sensorics/ui/device_main/ScanStatus.kt
  app/src/main/java/com/aconno/sensorics/viewmodel/DeviceViewModel.kt
  app/src/main/res/layout/activity_toolbar2.xml
  app/src/main/res/layout/fragment_device_main.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#166 Implement OTA(via BLE) Device Firmware Update
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/aconno/sensorics/DfuService.kt
  app/src/main/java/com/aconno/sensorics/Extensions.kt
  app/src/main/java/com/aconno/sensorics/dagger/application/ActivityBuilder.kt
  app/src/main/java/com/aconno/sensorics/dagger/dfu/DfuActivityScope.kt
  app/src/main/java/com/aconno/sensorics/ui/device_main/DeviceMainFragment.kt
  app/src/main/java/com/aconno/sensorics/ui/dfu/DfuActivity.kt
  app/src/main/java/com/aconno/sensorics/ui/dfu/NotificationActivity.kt
  app/src/main/res/anim/anim_fade_in.xml
  app/src/main/res/anim/anim_fade_out.xml
  app/src/main/res/anim/anim_slide_in_left.xml
  app/src/main/res/anim/anim_slide_in_right.xml
  app/src/main/res/anim/anim_slide_out_left.xml
  app/src/main/res/anim/anim_slide_out_right.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_file_upload_black_24dp.xml
  app/src/main/res/layout/activity_dfu.xml
  app/src/main/res/menu/menu_readings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#169 Viewpager connectable beacon
  app/src/main/AndroidManifest.xml
  app/src/main/assets/resources/configs/0300.config
  app/src/main/assets/resources/configs/18CF.config
  app/src/main/assets/resources/connection_screens/acnfreight.html
  app/src/main/assets/resources/device_screens/empty.html
  app/src/main/java/com/aconno/sensorics/BluetoothConnectService.kt
  app/src/main/java/com/aconno/sensorics/dagger/application/ActivityBuilder.kt
  app/src/main/java/com/aconno/sensorics/dagger/application/ResourcesModule.kt
  app/src/main/java/com/aconno/sensorics/dagger/connect/ConnectActivityModule.kt
  app/src/main/java/com/aconno/sensorics/dagger/connect/ConnectActivityScope.kt
  app/src/main/java/com/aconno/sensorics/ui/BleScanner.kt
  app/src/main/java/com/aconno/sensorics/ui/MainActivity2.kt
  app/src/main/java/com/aconno/sensorics/ui/connect/BluetoothServiceConnection.kt
  app/src/main/java/com/aconno/sensorics/ui/connect/ConnectActivity.kt
  app/src/main/java/com/aconno/sensorics/ui/device_main/DeviceMainFragment.kt
  app/src/main/java/com/aconno/sensorics/viewmodel/connection/ConnectionViewModel.kt
  app/src/main/java/com/aconno/sensorics/viewmodel/connection/ConnectionViewModelFactory.kt
  app/src/main/java/com/aconno/sensorics/viewmodel/resources/MainResourceViewModel.kt
  app/src/main/res/layout/activity_connect.xml
  app/src/main/res/menu/activity_connect.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/aconno/sensorics/data/mapper/ConfigFileJsonModelConverter.kt
  data/src/main/java/com/aconno/sensorics/data/repository/ResourcesInitializerImpl.kt
  data/src/main/java/com/aconno/sensorics/data/repository/resources/ConfigFileJsonModel.kt
  device/src/main/java/com/aconno/sensorics/device/bluetooth/BluetoothImpl.kt
  device/src/main/java/com/aconno/sensorics/device/notification/NotificationFactory.kt
  domain/src/main/java/com/aconno/sensorics/domain/interactor/resources/GetConnectionResourceUseCase.kt
  domain/src/main/java/com/aconno/sensorics/domain/model/ResourceConfig.kt
Labels: enhancement

#170 View pager usecases
  app/src/main/assets/resources/configs/0300.config
  app/src/main/assets/resources/configs/18CF.config
  app/src/main/assets/resources/device_screens/connect_empty.html
  app/src/main/java/com/aconno/sensorics/ui/device_main/DeviceMainFragment.kt
  app/src/main/res/anim/enter_from_left.xml
  app/src/main/res/anim/enter_from_right.xml
  app/src/main/res/anim/exit_to_left.xml
  app/src/main/res/anim/exit_to_right.xml
  app/src/main/res/drawable/ic_close_black_24dp.xml
  app/src/main/res/layout/fragment_device_main.xml
Labels: feature

#171 View pager dashboard
  app/src/main/java/com/aconno/sensorics/ui/welcome/WelcomeFragment.kt
  app/src/main/res/layout/fragment_welcome.xml
  app/src/main/res/menu/fragment_welcome.xml
Labels: feature

#172 View pager live graph
  app/src/main/java/com/aconno/sensorics/ui/device_main/DeviceMainFragment.kt
  app/src/main/java/com/aconno/sensorics/ui/livegraph/LiveGraphFragment.kt
  app/src/main/java/com/aconno/sensorics/viewmodel/LiveGraphViewModel.kt
  app/src/main/res/layout/fragment_device_main.xml
Labels: feature

#176 View pager connection fragment
  app/src/main/assets/resources/device_screens/acnangle.html
  app/src/main/java/com/aconno/sensorics/Extensions.kt
  app/src/main/java/com/aconno/sensorics/dagger/application/ActivityBuilder.kt
  app/src/main/java/com/aconno/sensorics/dagger/mainactivity/MainActivityFragmentsModule.kt
  app/src/main/java/com/aconno/sensorics/dagger/mainactivity/MainActivityModule.kt
  app/src/main/java/com/aconno/sensorics/ui/Connectable.kt
  app/src/main/java/com/aconno/sensorics/ui/MainActivity2.kt
  app/src/main/java/com/aconno/sensorics/ui/connect/BluetoothServiceConnection.kt
  app/src/main/java/com/aconno/sensorics/ui/connect/ConnectActivity.kt
  app/src/main/java/com/aconno/sensorics/ui/connect/ConnectFragment.kt
  app/src/main/java/com/aconno/sensorics/ui/device_main/DeviceMainFragment.kt
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_add_orange.xml
  app/src/main/res/layout/activity_connect.xml
  app/src/main/res/layout/activity_dfu.xml
  app/src/main/res/layout/fragment_device_main.xml
Labels: enhancement
